apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  namespace: gitlab
data:
  GITLAB_OMNIBUS_CONFIG: |
    external_url 'http://localhost:30080'
    gitlab_rails['db_adapter'] = 'postgresql'
    gitlab_rails['db_encoding'] = 'unicode'
    gitlab_rails['db_host'] = 'postgres-service'
    gitlab_rails['db_port'] = 5432
    gitlab_rails['db_database'] = 'gitlabhq_production'
    gitlab_rails['db_username'] = 'gitlab'
    puma['worker_processes'] = 2
    sidekiq['max_concurrency'] = 5
