apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runner-config-pvc
  namespace: gitlab
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-runner
  template:
    metadata:
      labels:
        app: gitlab-runner
    spec:
      containers:
        - name: gitlab-runner
          image: gitlab/gitlab-runner:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: runner-config-storage
              mountPath: /etc/gitlab-runner
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: runner-config-storage
          persistentVolumeClaim:
            claimName: runner-config-pvc
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
